dist: trusty
sudo: required
language: go
go:
- master
before_install:
- sudo add-apt-repository ppa:jonathonf/texlive-2016 -y
- sudo apt-get update -q
- sudo apt-get --no-install-recommends install texlive texlive-lang-german texlive-science
  texlive-latex-extra texlive-bibtex-extra biber texlive-generic-extra -y
install:
  - go get github.com/spf13/hugo
script:
- make clean
- make build
deploy:
  provider: releases
  api_key:
    secure: BBbDv0w8LO6fH91671NZG4ymqdiPG/L3lwJSq/3KLh/1bYineIrtVG5DkaBb+K5RXjoP6YqtJ+vtthw+VHtVl/NVqE9wMWE0uwhqyI6kSluJwwlN7FSa0s3NheluFw3vw+3Fxi84ozmbXG6TWBCNIDAQJ5xdqGbxj9AVLGa+qrMFDbHpJIPpbEmwX3zOp/Qh3MWw3no3LAZxw396/rRjAe66TqG4E42ZyTS5Ks8g95aZzjle54z2uQX1aHCRcjeoSfNbuY1Fcb/N0NN4+ucUwXuEdDPNNWEU6F7uxRCrjLRZufOl8YhzpDWFCWmE2Kmb/L3Eruq9JGaoh1gt16KhsLMMr9qiwES4gTaevhVuScttH45oQ/fOVawSSQ+8pMO3EicxVxOOF2Gj1yx9z6sf/xXZqCXzDS1/+rHf3g2UhUsxdUpitL77ZNBjU/bPG+f1RdLeM1fpH7vfwd4MRhRkhjl5vhBS5rz2yflKnELJ78qyThUqAXRDTP+NnEXQoFIiES9yWlzYngyTY4cGE9ZvOzPRjSKvD7crSl8wZI07yox5f2QVw7FW3aZ5iJ3M7Kr+kuyLvMdhyitlkmT/ndCY1fi1Lidtbib25qnBMYOKfjnUxPv5gMDX5akccucDLc4f9S3CisBDjTB3p6EhXGdj7Me0ocWUD3QOZmZug5TC06I=
  file: output/ai_script.pdf
  skip_cleanup: true
  on:
    repo: wysiib/ai_script
