baseURL = "/"
languageCode = "en-us"

title = "KI Skript"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
externalTitle = "External Links"
sidebarColor = "default"
customCss = []

[[menu.shortcuts]]
name = "Repository on Github"
url = "https://github.com/wysiib/ai_script"
weight = 10

[[menu.shortcuts]]
name = "Stups Lehrstuhl"
url = "http://stups.hhu.de"
weight = 20
